export interface ApiSnippet { name: string; sig: string; code: string }

export const API_SNIPPETS: ApiSnippet[] = [
  { name: 'rect',        sig: 'x, y, w, h, color?, opacity?, stroke?',               code: "rect(0.5, 0.5, 0.3, 0.3, '#8b5cf6', 0.85)" },
  { name: 'ellipse',     sig: 'x, y, w, h, color?, opacity?, stroke?',               code: "ellipse(0.5, 0.5, 0.3, 0.3, '#8b5cf6', 0.85)" },
  { name: 'triangle',    sig: 'x1,y1, x2,y2, x3,y3, color?, opacity?, stroke?',      code: "triangle(0.5, 0.1, 0.2, 0.9, 0.8, 0.9, '#8b5cf6', 0.85)" },
  { name: 'arc',         sig: 'cx, cy, r, startDeg, endDeg, color?, opacity?',       code: "arc(0.5, 0.5, 0.2, 0, 270, '#8b5cf6', 0.85)" },
  { name: 'line',        sig: 'x1, y1, x2, y2, color?, opacity?, width?',            code: "line(0.1, 0.5, 0.9, 0.5, '#8b5cf6', 0.85)" },
  { name: 'curve',       sig: 'x1, y1, cx, cy, x2, y2, color?, opacity?, width?',   code: "curve(0.1, 0.5, 0.5, 0.15, 0.9, 0.5, '#8b5cf6', 0.85)" },
  { name: 'spline',      sig: '[x1,y1,...], color?, opacity?, width?',               code: "spline([0.1, 0.3, 0.3, 0.7, 0.5, 0.4, 0.7, 0.7, 0.9, 0.3], '#8b5cf6', 0.85)" },
  { name: 'beginSpline', sig: '—',                                                   code: "beginSpline()\nrepeat(20, (i, t) => {\n  vertex(t, 0.3 + nz(t * 4) * 0.4)\n})\nendSpline('#8b5cf6', 0.85)" },
  { name: 'vertex',      sig: 'x, y',                                                code: "vertex(0.5, 0.3)" },
  { name: 'endSpline',   sig: 'color?, opacity?, width?',                            code: "endSpline('#8b5cf6', 0.85, 0.006)" },
  { name: 'nz',         sig: 'x, y? → 0..1',                                       code: "beginSpline()\nrepeat(20, (i, t) => {\n  vertex(t, 0.3 + nz(t * 4) * 0.4)\n})\nendSpline('#8b5cf6', 0.85)" },
  { name: 'stroke',     sig: 'hex, opacity?, width?, align?, join?',                 code: "stroke('#000000', 1, 0.005)" },
  { name: 'rotate',     sig: 'deg',                                                  code: "rotate(45)" },
  { name: 'transform',  sig: '{ rotate?, scaleX?, scaleY?, skewX?, skewY? }',       code: "transform({ rotate: 45, scaleX: 1.2 })" },
  { name: 'shadow',     sig: 'color?, opacity?, blur?, offsetX?, offsetY?',          code: "shadow('#000000', 0.5, 10, 0, 4)" },
  { name: 'blur',       sig: 'amount?',                                              code: "blur(4)" },
  { name: 'bevel',      sig: 'intensity?',                                           code: "bevel(0.6)" },
  { name: 'noise',      sig: 'amount?',                                              code: "noise(0.3)" },
  { name: 'warp',       sig: 'strength?, freq?',                                     code: "warp(8, 0.05)" },
  { name: 'grad',       sig: 'angle, …stops',                                        code: "grad(90, '#8b5cf6', '#4ecdc4')" },
  { name: 'radGrad',    sig: '…stops',                                               code: "radGrad('#8b5cf6', '#4ecdc4')" },
  { name: 'repeat',     sig: 'n, (i, t) => { }',                                    code: "repeat(8, (i, t) => {\n  rect((i + 0.5) / 8, 0.5, 0.1, 0.1)\n})" },
  { name: 'grid',       sig: 'cols, rows, (c, r, ct, rt) => { }',                   code: "grid(4, 4, (c, r) => {\n  rect((c + 0.5) / 4, (r + 0.5) / 4, 0.2, 0.2)\n})" },
  { name: 'wave',       sig: 'n, amplitude, frequency, (i, t, x, y) => { }',        code: "wave(16, 0.2, 1.5, (i, t, x, y) => {\n  ellipse(x, y, 0.04, 0.04, '#8b5cf6', 0.85)\n})" },
  { name: 'circular',   sig: 'n, cx, cy, r, (i, t, x, y, angle) => { }',           code: "circular(12, 0.5, 0.5, 0.35, (i, t, x, y, angle) => {\n  ellipse(x, y, 0.06, 0.06, '#8b5cf6', 0.85)\n})" },
]
