import type { Pattern } from '../layers/types'

export const BUILTIN_PATTERNS: Pattern[] = [
  {
    id: 'builtin-grid-rects',
    name: 'Tile Grid',
    type: 'grid',
    shape: 'rect',
    color: '#8b5cf6',
    opacity: 0.85,
    count: 8,
    cols: 4,
    rows: 4,
    builtin: true,
  },
  {
    id: 'builtin-dot-row',
    name: 'Dot Row',
    type: 'row',
    shape: 'ellipse',
    color: '#4ecdc4',
    opacity: 0.9,
    count: 12,
    cols: 4,
    rows: 4,
    builtin: true,
  },
  {
    id: 'builtin-circular',
    name: 'Radial Ring',
    type: 'circular',
    shape: 'ellipse',
    color: '#f7c68a',
    opacity: 0.85,
    count: 10,
    cols: 4,
    rows: 4,
    builtin: true,
  },
  {
    id: 'builtin-spiral',
    name: 'Spiral',
    type: 'spiral',
    shape: 'rect',
    color: '#ff2d78',
    opacity: 0.8,
    count: 24,
    cols: 4,
    rows: 4,
    builtin: true,
  },
  {
    id: 'builtin-wave',
    name: 'Wave',
    type: 'wave',
    shape: 'ellipse',
    color: '#2d6aff',
    opacity: 0.85,
    count: 16,
    cols: 4,
    rows: 4,
    builtin: true,
  },
  {
    id: 'builtin-tri-grid',
    name: 'Triangle Grid',
    type: 'grid',
    shape: 'triangle',
    color: '#c84b7f',
    opacity: 0.85,
    count: 8,
    cols: 5,
    rows: 5,
    builtin: true,
  },
]
